# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-18 10:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=20)),
                ('country_code', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.IntegerField(default=0)),
                ('tag_code', models.CharField(default='NA', max_length=50)),
                ('year', models.IntegerField(default=0)),
                ('january', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('february', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('march', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('april', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('may', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('june', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('july', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('august', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('september', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('october', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('november', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('december', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('winter', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('spring', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('summer', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('autumn', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('annual', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
